name: Automação Planilha
on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 10-18 * * 1-5'
    
jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_KEY_ROLESECRET: ${{ secrets.SUPABASE_KEY_ROLESECRET }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: stable
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.18.1 webdriver_manager==4.0.1
          pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python automacao.py
