name: Automação Comissão
on:
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * 1-5'  # 10:15
    - cron: '45 11 * * 1-5'  # 11:45
    - cron: '15 13 * * 1-5'  # 13:15
    - cron: '45 14 * * 1-5'  # 14:45
    - cron: '15 16 * * 1-5'  # 16:15
    - cron: '45 17 * * 1-5'  # 17:45

jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: 131
          install-chromedriver: 131.0.6778.264
          
      - name: Instalar dependências
        run: pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python automacao_comissao.py
