name: Automação Planilha
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1-5'  # 10:00
    - cron: '30 11 * * 1-5' # 11:30
    - cron: '0 13 * * 1-5'  # 13:00
    - cron: '30 14 * * 1-5' # 14:30
    - cron: '0 16 * * 1-5'  # 16:00
    - cron: '30 17 * * 1-5' # 17:30
jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all    # Adicionando permissões explícitas
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_KEY_ROLESECRET: ${{ secrets.SUPABASE_KEY_ROLESECRET }}  # Adicionar esta linha
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: stable
          install-chromedriver: true
          
      - name: Instalar dependências
        run: pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python automacao.py
