name: Automação Planilha

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1-5'

jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: stable
          install-chromedriver: true
          
      - name: Instalar dependências
        run: pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python automacao.py
