name: Automação Planilha
on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 10-18 * * 1-5'
    
jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_KEY_ROLESECRET: ${{ secrets.SUPABASE_KEY_ROLESECRET }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: 131
          install-chromedriver: 131.0.6778.264
          
      - name: Instalar dependências
        run: pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python automacao.py
