name: Automação Planilha
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1-5'  # Corrigido o espaço entre * e 1-5
jobs:
  executar-automacao:
    runs-on: ubuntu-latest
    permissions: write-all    # Adicionando permissões explícitas
    
    env:
      LOGIN: ${{ secrets.LOGIN }}
      SENHA: ${{ secrets.SENHA }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
        with:
          chrome-version: stable
          install-chromedriver: true
          
      - name: Instalar dependências
        run: pip install -r requirements.txt
          
      - name: Executar script de automação
        run: python automacao.py
